### PR TITLE
Rewrite the affinity control fix to lock game threads to one core, leaving others free

### LINKED ISSUE #11: CPU Affinity
Just wanted to inform you and maybe help others! With Patch 1.002 installed and your SilentPatch the Game starts with all Cores checked in the Task Manager. This caused a bug for me, where i was not able to Load my Profile because it simply showed no Text. The Window was there, but i could only press ESC to start a new Game. When i start a new Game, minimize it immediately after the start, and select only 1 Core in the Task Manager, it shows the Text for loading my Profile. This does not happen with Version 1.0 and your Patch because with this Version only 1 Core is already checked. I maybe know why this happens, this could be caused by AMD's Ryzen CPU Count which is different from other CPU's. Also another issue i have is that the Sun Flickers inside and outside of the World which does not happen when i use the Wine Glider Solution.
Bug1
Bug2
SunBug

### LINKED ISSUE #16: Blank red box glitch
Hey I would like to say first thank you so much for making this :D wish this was around back when I didn't have to do the 1 core thingy haha :D 

There is only one issue I'm having and idk if its been reported or if theres a perm fix for it but after i save my game come back to it later I can't load my profile/save. When loading the game it gives me a blank red box and makes me start over. The only way I can load my save is by uninstalling the game and reinstalling it.

I did some reading into it but it doesn't apply to me since I play on keyboard and mouse any idea on how to fix or if their will be a patch to fix this bug? Thanks so much for taking the time and reading this.

### PR DESCRIPTION
**Pull request by CookiePLMonster**
Heavily based on an identical fix for NFS Underground 2:
https://github.com/ThirteenAG/WidescreenFixesPack/pull/1045
My approach is identical, but also leans heavily on safety - by ensuring the thread doesn't start before affinity is changed and by not messing with affinity if there's not enough cores available for the game.

Also adds an "emergency" `SingleCoreAffinity` option to the INI, can be used in an unlikely case this change still causes issues.

Based on my limited testing, this seems to combine good stability of running the game on a single core **and** performance benefits of letting it run free. Hopefully this approach means the game works fine for those who previously had bugs introduced by SP.
Scarface_TJPzy1BHWq

Fixes #11 
Fixes #16

### CODE REVIEW

**Comment by ThirteenAG** [comment]
Maybe add `namespace AffinityChanges` to modutils? Then we can reuse that code whenever necessary, since it doesn't rely on anything specific to exe. And in case of any new ideas/improvements, it can be updated there.

**Comment by CookiePLMonster** [comment]
> it doesn't rely on anything specific to exe.

It actually does, just indirectly:
1. Games with code in DLL will be unaffected and this might give a false sense of fixing things.
2. Notice my code differs from the one in UG2 - as the OriginalFirstThunk is gone in Scarface.

**Comment by ThirteenAG** [comment]
> Games with code in DLL will be unaffected and this might give a false sense of fixing things.

`RedirectImports(HANDLE module)` or something?

> Notice my code differs from the one in UG2 - as the OriginalFirstThunk is gone in Scarface.

Shouldn't be a problem to account for both cases though?

**Comment by Sagatt** [comment]
Other issues within the game such as draw distance (culling), some textures not rendering properly, voices getting high pitched if you pass by someone in a high speed car etc could be addressed too?

**Comment by CookiePLMonster** [comment]
> Other issues within the game such as draw distance (culling), some textures not rendering properly, voices getting high pitched if you pass by someone in a high speed car etc could be addressed too?

No, unlikely. I'm not currently interested in adding new fixes, I just want to make sure the current ones don't regress the game.

**Comment by Sagatt** [comment]
That is sad, good luck tho, without your efforts and widescreenAG this game would be unplayable and the remastered project too

**Comment by PatrickvL** [comment]
Isn't this much like what we do in CxbxReloaded as well?

**Comment by CookiePLMonster** [comment]
Yep it is! It's just less strict, since I don't bother keeping the other threads away from the core used by game threads.

**Comment by PatrickvL** [comment]
Btw, wasn't there some sort of un-protecting needed and CPU cache flushing, before and after the thunk table is patched?

**Comment by CookiePLMonster** [comment]
IAT is data so not really.

**Comment by CookiePLMonster** [comment]
Numerous people confirmed it improves stability, it's good to go.

**Comment by Lagahan** [comment]
Getting an assertion failed on boot:
image

**Comment by CookiePLMonster** [comment]
Oh, interesting! What is that executable?

I'll fix it for release, thanks for letting me know. I'm wrapping up the release as we speak but this will be an easy change since I already have code for this used elsewhere.

**Comment by Lagahan** [comment]
Not sure, looks like 1.0.0.1 - installed this way back when your first patch came out. 
image

Also using aap's XDinput for xbox controller input, just in case they're stepping on each other.

**Comment by CookiePLMonster** [comment]
Can you try with this instead?
[snip]

I'm preparing the release right now so it's literally a last minute change.

**Comment by Lagahan** [comment]
Yep, back ingame now!

**Comment by CookiePLMonster** [comment]
Thanks! We're good to go then.

**Comment by Aamember12403** [comment]
So is there a new silent patch that addresses the previous issues with loading the save on start?

**Comment by CookiePLMonster** [comment]
Yes, I believe this PR has resolved them. It's now out officially:
https://cookieplmonster.github.io/mods/scarface/

**Comment by Aamember12403** [comment]
Thank you sir you are a god amongst men..

**Pull request merged**
